# Generated by Django 4.2.2 on 2023-07-07 05:57

import ckeditor.fields
import django.db.models.deletion
import django.db.models.manager
import mptt.fields
from django.conf import settings
from django.db import migrations, models

import products.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "sub_categoty",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Product ID",
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("isbn", "ISBN"),
                            ("ean", "EAN"),
                            ("gtin", "GTIN"),
                            ("upc", "UPC"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(blank=True)),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to=products.utils.thumbnail_directory_path
                    ),
                ),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("out_of_stack", "Out of stack"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.category",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            managers=[
                ("published_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProductQuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qa",
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_1",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.utils.photo_1_directory_path,
                    ),
                ),
                (
                    "image_2",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.utils.photo_2_directory_path,
                    ),
                ),
                (
                    "image_3",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.utils.photo_3_directory_path,
                    ),
                ),
                (
                    "image_4",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.utils.photo_4_directory_path,
                    ),
                ),
                (
                    "image_5",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.utils.photo_5_directory_path,
                    ),
                ),
                (
                    "image_6",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.utils.photo_6_directory_path,
                    ),
                ),
                (
                    "image_7",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.utils.photo_7_directory_path,
                    ),
                ),
                (
                    "image_8",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.utils.photo_8_directory_path,
                    ),
                ),
                (
                    "image_9",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.utils.photo_9_directory_path,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
