# Generated by Django 4.2.2 on 2023-07-08 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="sub_categoty",
            new_name="parent",
        ),
    ]
