# Generated by Django 4.2.2 on 2023-07-09 05:40

from django.db import migrations, models

import products.utils


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_rename_sub_categoty_category_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="productimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=products.utils.thumbnail_directory_path
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
